### ISSUE TITLE
Notifications are sent

### ISSUE THREAD

**Issue by malago86** [clarkwinkelmann/flarum-ext-shadow-ban#4]
Hello!

Two suggestions that I would like to see in the future :)

- When a shadow banned user makes a new post, notifications are sent to those users that are following that discussion, when they enter, there is nothing to see
- The discussion lists seems to be showing who was the last poster and it shows up as the shadow banned user, confusing users that go in and don't see that post anywhere

Thanks for this great extension again!

**Comment by clarkwinkelmann** [comment]
Thanks for the report!

Yep, we definitely don't want that. I will see how I can fix them.

The notification issue is probably linked to similar issues we have in Flarum itself with approval. We don't have a good system in place to choose who should be notified for something not everyone can see.

**Comment by clarkwinkelmann** [comment]
The two issues are fixed in the new 1.1.0 version!

There might still be notifications from other community extensions that will show the content, I'll add more explicit silencing if needed. I think all notifications from core extensions are now covered.

Unfortunately hiding posts from the discussion meta does gives a few hints to the shadow-banned user that they are shadow banned, but it's definitely better this way as to not confuse the regular user base and also not bump discussions to the top.
